[package]
name = "photosphere"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "photosphere"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
clap = { version = "3.1.18", features = ["derive"] }
